### ISSUE TITLE
Search history buttons

### ISSUE THREAD

**Issue by bryannolasco11** [Crackerbox123/Group_Cool#8]
Keeping a search history up to five plants and creating buttons which will be clickable to send through the program again.

**Comment by strossouw** [comment]
Buttons have been created in HTML. They need the JS actions added. 
![image](https://user-images.githubusercontent.com/105831699/178107695-579df9a9-30ff-4b2b-9a65-5d8b2af5d379.png)


Append the search history to this div. JS should create a new div.
I will add bulma stying to JS after button actions are functional.
![image](https://user-images.githubusercontent.com/105831699/178107543-5aba6147-3fc8-468d-be4d-131edbab482e.png)
